language: node_js
node_js:
  - 16
install:
  - npm i
script:
  - npm run build
  - cat index.js
  - ls -r node_modules
deploy:
  provider: lambda
  function_name: "my-test-function-travis-lambda"
  region: "us-east-1"
  role: "arn:aws:iam::208369778572:role/lambda-ex"
  runtime: "nodejs12.x"
  handler_name: "handler"
  zip-file: "fileb://function.zip"